### ISSUE TITLE
Use exit code to return run information

### ISSUE THREAD

**Issue by alexjurkiewicz** [santana/puppet-cleaner#11]
Hi, I still use this tool a lot! I'd like to automate it as part of a pre-commit hook for our puppet repo, where commits will be forbidden if puppet-clean finds problems.

Could a mode like -q,--quiet be added where nothing is output, but an exit code of 1 is returned if any files are modified?

**Comment by santana** [comment]
Hi @alexjurkiewicz , thanks for trying puppet-cleaner!

It's an interesting idea what you propose, since puppet-cleaner was not conceived as a tool for detecting issues but for fixing them. Yet it may be adapted as such as you describe.

There are some caveats though, inherent to the way it parses the manifests:

a) it won't notice the change of $var to ${var} inside strings

  the puppet parser, which is used by puppet-cleaner, understands variables inside strings, even without ${}. Once parsed, puppet-cleaner ignores what the original representation was, and decides to represent $var as ${var}. But since no token transformation occurs, it doesn't count as a modification.

b) it won't notice the change of double quotes to single quotes either

  exactly for the same reason.

Do you think a tool with these caveats would still be useful to you?

**Comment by alexjurkiewicz** [comment]
Would it be possible for detect these changes by having puppet-cleaner compare what it outputs to the original input file? Just diffing the two strings would detect "there was a change", right?

But even if this isn't feasible I think such a feature would still be useful. I already run files through puppet-lint, but the two tools complement each other.

**Comment by santana** [comment]
Yes, comparing input and output would do the trick; it would be no different from sending the output to a file and using diff -q though.

Yet if puppet-cleaner takes this task, it may improve the response time by returning sooner if a change in the stream of tokens is detected. It's feasible indeed.
